#pragma once

#include "effector.hpp"

#include "bypass.hpp"
#include "amp.hpp"
#include "chorus.hpp"
#include "comb_filter.hpp"
#include "cruncher.hpp"
#include "crusher.hpp"
#include "delay.hpp"
#include "differentiator.hpp"
#include "dynamics_processor.hpp"
#include "fir_filter.hpp"
#include "flanger.hpp"
#include "iir_filter.hpp"
#include "level_detector.hpp"
#include "octaver.hpp"
#include "oscillator.hpp"
#include "oversampling_processor.hpp"
#include "phaser.hpp"
#include "pitch_detector.hpp"
#include "reverb.hpp"
#include "shaper.hpp"
#include "super_wave_oscillator.hpp"